export const jobs = [
  {
    jobId: "49790139",
    jobTitle: "Corporate Integration Executive",
    jobArea: "Markets",
    jobCompany: "Howell and Sons",
  },
  {
    jobId: "63958436",
    jobTitle: "Global Implementation Architect",
    jobArea: "Accountability",
    jobCompany: "Balistreri LLC",
  },
  {
    jobId: "69445419",
    jobTitle: "Dynamic Accounts Assistant",
    jobArea: "Assurance",
    jobCompany: "Schmitt, Haley and Bosco",
  },
  {
    jobId: "65888808",
    jobTitle: "Lead Response Officer",
    jobArea: "Brand",
    jobCompany: "Osinski, Boyle and Medhurst",
  },
  {
    jobId: "46945162",
    jobTitle: "Product Marketing Developer",
    jobArea: "Accounts",
    jobCompany: "Jerde, Auer and Barton",
  },
  {
    jobId: "76967224",
    jobTitle: "Forward Integration Executive",
    jobArea: "Brand",
    jobCompany: "Koss - Upton",
  },
  {
    jobId: "02921150",
    jobTitle: "Senior Quality Agent",
    jobArea: "Implementation",
    jobCompany: "Gleason, Gusikowski and Kulas",
  },
  {
    jobId: "50556195",
    jobTitle: "Future Quality Manager",
    jobArea: "Security",
    jobCompany: "Jerde - Wiegand",
  },
  {
    jobId: "64450750",
    jobTitle: "Investor Marketing Analyst",
    jobArea: "Data",
    jobCompany: "Bartell, McGlynn and Tillman",
  },
  {
    jobId: "95141883",
    jobTitle: "Regional Operations Officer",
    jobArea: "Branding",
    jobCompany: "Hessel, Heidenreich and Marquardt",
  },
  {
    jobId: "76718666",
    jobTitle: "Legacy Identity Director",
    jobArea: "Accounts",
    jobCompany: "Hermiston Group",
  },
  {
    jobId: "74890646",
    jobTitle: "Senior Research Consultant",
    jobArea: "Usability",
    jobCompany: "Kirlin and Sons",
  },
  {
    jobId: "59432797",
    jobTitle: "Customer Paradigm Supervisor",
    jobArea: "Accounts",
    jobCompany: "Cremin - Hansen",
  },
  {
    jobId: "55087349",
    jobTitle: "Forward Web Architect",
    jobArea: "Solutions",
    jobCompany: "Ward Group",
  },
  {
    jobId: "65901417",
    jobTitle: "Chief Implementation Developer",
    jobArea: "Applications",
    jobCompany: "Fay Group",
  },
  {
    jobId: "57290751",
    jobTitle: "Corporate Solutions Coordinator",
    jobArea: "Solutions",
    jobCompany: "Barrows LLC",
  },
  {
    jobId: "21825259",
    jobTitle: "Internal Response Liaison",
    jobArea: "Integration",
    jobCompany: "Bosco LLC",
  },
  {
    jobId: "59453088",
    jobTitle: "Product Integration Developer",
    jobArea: "Data",
    jobCompany: "Howell - Kautzer",
  },
  {
    jobId: "87745413",
    jobTitle: "Senior Marketing Liaison",
    jobArea: "Factors",
    jobCompany: "Von Inc",
  },
  {
    jobId: "72670560",
    jobTitle: "Direct Brand Specialist",
    jobArea: "Usability",
    jobCompany: "Mante - Goodwin",
  },
];
