export const consultants = [
  {
    id: "JOBSNV0001",
    firstName: "Alice",
    lastName: "Smith",
    email: "alice.smith@example.com",
    phone: "+91-9876543211",
    addressStreet: "123 Main St",
    addressCity: "Mumbai",
    addressDistrict: "Mumbai Suburban",
    addressState: "Maharashtra",
    addressCountry: "India",
    position: "Senior Consultant",
    salary: "15 LPA",
    dateOfBirth: "1985-04-22",
    profilePic: "profilepic_alice.jpg",
    startDate: "2020-01-15",
    endDate: null,
    workingLocation: "Mumbai",
    currentPotentialPoints: 120.5,
    cumulativePotentialPoints: 450.75,
    createdAt: "2020-01-01T10:00:00Z",
    updatedAt: "2024-08-01T10:00:00Z",
  },
  {
    id: "JOBSNV0002",
    firstName: "Bob",
    lastName: "Johnson",
    email: "bob.johnson@example.com",
    phone: "+91-9876543212",
    addressStreet: "456 Elm St",
    addressCity: "Delhi",
    addressDistrict: "New Delhi",
    addressState: "Delhi",
    addressCountry: "India",
    position: "Junior Consultant",
    salary: "8 LPA",
    dateOfBirth: "1992-07-10",
    profilePic: "profilepic_bob.jpg",
    startDate: "2021-03-20",
    endDate: null,
    workingLocation: "Delhi",
    currentPotentialPoints: 80.0,
    cumulativePotentialPoints: 300.0,
    createdAt: "2021-03-01T09:00:00Z",
    updatedAt: "2024-08-01T09:00:00Z",
  },
  {
    id: "JOBSNV0003",
    firstName: "Carol",
    lastName: "Williams",
    email: "carol.williams@example.com",
    phone: "+91-9876543213",
    addressStreet: "789 Pine St",
    addressCity: "Chennai",
    addressDistrict: "Chennai",
    addressState: "Tamil Nadu",
    addressCountry: "India",
    position: "Consultant",
    salary: "10 LPA",
    dateOfBirth: "1988-02-15",
    profilePic: "profilepic_carol.jpg",
    startDate: "2019-05-10",
    endDate: null,
    workingLocation: "Chennai",
    currentPotentialPoints: 95.0,
    cumulativePotentialPoints: 400.0,
    createdAt: "2019-05-01T08:00:00Z",
    updatedAt: "2024-08-01T08:00:00Z",
  },
  {
    id: "JOBSNV0004",
    firstName: "David",
    lastName: "Brown",
    email: "david.brown@example.com",
    phone: "+91-9876543214",
    addressStreet: "101 Maple St",
    addressCity: "Kolkata",
    addressDistrict: "Kolkata",
    addressState: "West Bengal",
    addressCountry: "India",
    position: "Lead Consultant",
    salary: "18 LPA",
    dateOfBirth: "1983-11-20",
    profilePic: "profilepic_david.jpg",
    startDate: "2018-07-01",
    endDate: null,
    workingLocation: "Kolkata",
    currentPotentialPoints: 150.0,
    cumulativePotentialPoints: 600.0,
    createdAt: "2018-07-01T07:00:00Z",
    updatedAt: "2024-08-01T07:00:00Z",
  },
  {
    id: "JOBSNV0005",
    firstName: "Eve",
    lastName: "Davis",
    email: "eve.davis@example.com",
    phone: "+91-9876543215",
    addressStreet: "202 Birch St",
    addressCity: "Hyderabad",
    addressDistrict: "Hyderabad",
    addressState: "Telangana",
    addressCountry: "India",
    position: "Consultant",
    salary: "12 LPA",
    dateOfBirth: "1990-09-10",
    profilePic: "profilepic_eve.jpg",
    startDate: "2020-09-01",
    endDate: null,
    workingLocation: "Hyderabad",
    currentPotentialPoints: 110.0,
    cumulativePotentialPoints: 450.0,
    createdAt: "2020-09-01T06:00:00Z",
    updatedAt: "2024-08-01T06:00:00Z",
  },
  {
    id: "JOBSNV0006",
    firstName: "Frank",
    lastName: "Miller",
    email: "frank.miller@example.com",
    phone: "+91-9876543216",
    addressStreet: "303 Cedar St",
    addressCity: "Bangalore",
    addressDistrict: "Bangalore Urban",
    addressState: "Karnataka",
    addressCountry: "India",
    position: "Senior Consultant",
    salary: "14 LPA",
    dateOfBirth: "1987-03-05",
    profilePic: "profilepic_frank.jpg",
    startDate: "2017-04-10",
    endDate: null,
    workingLocation: "Bangalore",
    currentPotentialPoints: 130.0,
    cumulativePotentialPoints: 500.0,
    createdAt: "2017-04-01T05:00:00Z",
    updatedAt: "2024-08-01T05:00:00Z",
  },
  {
    id: "JOBSNV0007",
    firstName: "Grace",
    lastName: "Wilson",
    email: "grace.wilson@example.com",
    phone: "+91-9876543217",
    addressStreet: "404 Spruce St",
    addressCity: "Ahmedabad",
    addressDistrict: "Ahmedabad",
    addressState: "Gujarat",
    addressCountry: "India",
    position: "Consultant",
    salary: "11 LPA",
    dateOfBirth: "1989-06-18",
    profilePic: "profilepic_grace.jpg",
    startDate: "2021-02-15",
    endDate: null,
    workingLocation: "Ahmedabad",
    currentPotentialPoints: 100.0,
    cumulativePotentialPoints: 410.0,
    createdAt: "2021-02-01T04:00:00Z",
    updatedAt: "2024-08-01T04:00:00Z",
  },
  {
    id: "JOBSNV0008",
    firstName: "Hank",
    lastName: "Moore",
    email: "hank.moore@example.com",
    phone: "+91-9876543218",
    addressStreet: "505 Pineapple St",
    addressCity: "Pune",
    addressDistrict: "Pune",
    addressState: "Maharashtra",
    addressCountry: "India",
    position: "Junior Consultant",
    salary: "9 LPA",
    dateOfBirth: "1993-12-14",
    profilePic: "profilepic_hank.jpg",
    startDate: "2022-01-20",
    endDate: null,
    workingLocation: "Pune",
    currentPotentialPoints: 70.0,
    cumulativePotentialPoints: 280.0,
    createdAt: "2022-01-01T03:00:00Z",
    updatedAt: "2024-08-01T03:00:00Z",
  },
  {
    id: "JOBSNV0009",
    firstName: "Ivy",
    lastName: "Taylor",
    email: "ivy.taylor@example.com",
    phone: "+91-9876543219",
    addressStreet: "606 Oak St",
    addressCity: "Gurgaon",
    addressDistrict: "Gurgaon",
    addressState: "Haryana",
    addressCountry: "India",
    position: "Consultant",
    salary: "13 LPA",
    dateOfBirth: "1991-11-05",
    profilePic: "profilepic_ivy.jpg",
    startDate: "2019-10-15",
    endDate: null,
    workingLocation: "Gurgaon",
    currentPotentialPoints: 105.0,
    cumulativePotentialPoints: 420.0,
    createdAt: "2019-10-01T02:00:00Z",
    updatedAt: "2024-08-01T02:00:00Z",
  },
  {
    id: "JOBSNV0010",
    firstName: "Jack",
    lastName: "Anderson",
    email: "jack.anderson@example.com",
    phone: "+91-9876543220",
    addressStreet: "707 Palm St",
    addressCity: "Noida",
    addressDistrict: "Gautam Buddha Nagar",
    addressState: "Uttar Pradesh",
    addressCountry: "India",
    position: "Lead Consultant",
    salary: "17 LPA",
    dateOfBirth: "1986-08-25",
    profilePic: "profilepic_jack.jpg",
    startDate: "2018-12-01",
    endDate: null,
    workingLocation: "Noida",
    currentPotentialPoints: 140.0,
    cumulativePotentialPoints: 550.0,
    createdAt: "2018-12-01T01:00:00Z",
    updatedAt: "2024-08-01T01:00:00Z",
  },
];

export const sectorsData = [
  { value: "BPM_BPO", label: "BPM / BPO" },
  { value: "ANALYTICS_KPO_RESEARCH", label: "Analytics / KPO / Research" },
  { value: "IT_SERVICES", label: "IT Services" },
  { value: "IT_SERVICES_CONSULTING", label: "IT Services & Consulting" },
  { value: "TECHNOLOGY", label: "Technology" },
  {
    value: "ELECTRONIC_COMPONENTS_SEMICONDUCTORS",
    label: "Electronic Components / Semiconductors",
  },
  { value: "ELECTRONICS_MANUFACTURING", label: "Electronics Manufacturing" },
  { value: "EMERGING_TECHNOLOGIES", label: "Emerging Technologies" },
  { value: "HARDWARE_NETWORKING", label: "Hardware & Networking" },
  { value: "INTERNET", label: "Internet" },
  { value: "SOFTWARE_PRODUCT", label: "Software Product" },
  { value: "BFSI", label: "BFSI" },
  { value: "BANKING", label: "Banking" },
  { value: "FINANCIAL_SERVICES", label: "Financial Services" },
  { value: "FINTECH_PAYMENTS", label: "FinTech / Payments" },
  { value: "INSURANCE", label: "Insurance" },
  {
    value: "INVESTMENT_BANKING_VC_PE",
    label: "Investment Banking / Venture Capital / Private Equity",
  },
  { value: "NBFC", label: "NBFC" },
  { value: "EDUCATION", label: "Education" },
  { value: "EDUCATION_TRAINING", label: "Education / Training" },
  { value: "E_LEARNING_EDTECH", label: "E-Learning / EdTech" },
  { value: "MANUFACTURING_PRODUCTION", label: "Manufacturing & Production" },
  { value: "AUTO_COMPONENTS", label: "Auto Components" },
  { value: "AUTOMOBILE", label: "Automobile" },
  { value: "BUILDING_MATERIAL", label: "Building Material" },
  { value: "CHEMICALS", label: "Chemicals" },
  { value: "DEFENCE_AEROSPACE", label: "Defence & Aerospace" },
  { value: "ELECTRICAL_EQUIPMENT", label: "Electrical Equipment" },
  {
    value: "FERTILIZERS_PESTICIDES_AGRO_CHEMICALS",
    label: "Fertilizers / Pesticides / Agro chemicals",
  },
  { value: "INDUSTRIAL_AUTOMATION", label: "Industrial Automation" },
  {
    value: "INDUSTRIAL_EQUIPMENT_MACHINERY",
    label: "Industrial Equipment / Machinery",
  },
  { value: "IRON_STEEL", label: "Iron & Steel" },
  { value: "METALS_MINING", label: "Metals & Mining" },
  { value: "PACKAGING_CONTAINERS", label: "Packaging & Containers" },
  {
    value: "PETROCHEMICAL_PLASTICS_RUBBER",
    label: "Petrochemical / Plastics / Rubber",
  },
  { value: "PULP_PAPER", label: "Pulp & Paper" },
  {
    value: "INFRASTRUCTURE_TRANSPORT_REAL_ESTATE",
    label: "Infrastructure, Transport & Real Estate",
  },
  { value: "AVIATION", label: "Aviation" },
  { value: "COURIER_LOGISTICS", label: "Courier / Logistics" },
  { value: "ENGINEERING_CONSTRUCTION", label: "Engineering & Construction" },
  { value: "OIL_GAS", label: "Oil & Gas" },
  { value: "PORTS_SHIPPING", label: "Ports & Shipping" },
  { value: "POWER", label: "Power" },
  { value: "RAILWAYS", label: "Railways" },
  { value: "REAL_ESTATE", label: "Real Estate" },
  { value: "URBAN_TRANSPORT", label: "Urban Transport" },
  {
    value: "WATER_TREATMENT_WASTE_MANAGEMENT",
    label: "Water Treatment / Waste Management",
  },
  {
    value: "CONSUMER_RETAIL_HOSPITALITY",
    label: "Consumer, Retail & Hospitality",
  },
  { value: "BEAUTY_PERSONAL_CARE", label: "Beauty & Personal Care" },
  { value: "BEVERAGE", label: "Beverage" },
  {
    value: "CONSUMER_ELECTRONICS_APPLIANCES",
    label: "Consumer Electronics & Appliances",
  },
  { value: "FITNESS_WELLNESS", label: "Fitness & Wellness" },
  { value: "FMCG", label: "FMCG" },
  { value: "FOOD_PROCESSING", label: "Food Processing" },
  { value: "FURNITURE_FURNISHING", label: "Furniture & Furnishing" },
  { value: "GEMS_JEWELLERY", label: "Gems & Jewellery" },
  { value: "HOTELS_RESTAURANTS", label: "Hotels & Restaurants" },
  { value: "LEATHER", label: "Leather" },
  { value: "RETAIL", label: "Retail" },
  { value: "TEXTILE_APPAREL", label: "Textile & Apparel" },
  { value: "TRAVEL_TOURISM", label: "Travel & Tourism" },
  { value: "HEALTHCARE_LIFE_SCIENCES", label: "Healthcare & Life Sciences" },
  { value: "BIOTECHNOLOGY", label: "Biotechnology" },
  {
    value: "CLINICAL_RESEARCH_CONTRACT_RESEARCH",
    label: "Clinical Research / Contract Research",
  },
  { value: "MEDICAL_DEVICES_EQUIPMENT", label: "Medical Devices & Equipment" },
  { value: "MEDICAL_SERVICES_HOSPITAL", label: "Medical Services / Hospital" },
  {
    value: "PHARMACEUTICAL_LIFE_SCIENCES",
    label: "Pharmaceutical & Life Sciences",
  },
  {
    value: "MEDIA_ENTERTAINMENT_TELECOM",
    label: "Media, Entertainment & Telecom",
  },
  { value: "ADVERTISING_MARKETING", label: "Advertising & Marketing" },
  { value: "ANIMATION_VFX", label: "Animation & VFX" },
  { value: "EVENTS_LIVE_ENTERTAINMENT", label: "Events / Live Entertainment" },
  { value: "FILM_MUSIC_ENTERTAINMENT", label: "Film / Music / Entertainment" },
  { value: "GAMING", label: "Gaming" },
  { value: "PRINTING_PUBLISHING", label: "Printing & Publishing" },
  {
    value: "SPORTS_LEISURE_RECREATION",
    label: "Sports / Leisure & Recreation",
  },
  { value: "TELECOM_ISP", label: "Telecom / ISP" },
  { value: "TV_RADIO", label: "TV / Radio" },
  { value: "PROFESSIONAL_SERVICES", label: "Professional Services" },
  { value: "ACCOUNTING_AUDITING", label: "Accounting / Auditing" },
  {
    value: "ARCHITECTURE_INTERIOR_DESIGN",
    label: "Architecture / Interior Design",
  },
  {
    value: "CONTENT_DEVELOPMENT_LANGUAGE",
    label: "Content Development / Language",
  },
  { value: "DESIGN", label: "Design" },
  {
    value: "FACILITY_MANAGEMENT_SERVICES",
    label: "Facility Management Services",
  },
  { value: "LEGAL", label: "Legal" },
  { value: "MANAGEMENT_CONSULTING", label: "Management Consulting" },
  { value: "RECRUITMENT_STAFFING", label: "Recruitment / Staffing" },
  { value: "MISCELLANEOUS", label: "Miscellaneous" },
  {
    value: "AGRICULTURE_FORESTRY_FISHING",
    label: "Agriculture / Forestry / Fishing",
  },
  {
    value: "GOVERNMENT_PUBLIC_ADMINISTRATION",
    label: "Government / Public Administration",
  },
  { value: "IMPORT_EXPORT", label: "Import & Export" },
  {
    value: "NGO_SOCIAL_SERVICES_INDUSTRY_ASSOCIATIONS",
    label: "NGO / Social Services / Industry Associations",
  },
];

export const domainsData = [
  { value: "BANKING_OPERATIONS", label: "Banking Operations" },
  { value: "ACQUISITION_MANAGER", label: "Acquisition Manager" },
  { value: "AREA_TERRITORY_MANAGER", label: "Area / Territory Manager" },
  { value: "ASSET_OPERATIONS", label: "Asset Operations" },
  { value: "ATM_OPERATIONS_MANAGER", label: "ATM Operations Manager" },
  { value: "BACK_OFFICE_EXECUTIVE", label: "Back Office Executive" },
  { value: "BANK_TELLER_CLERK", label: "Bank Teller / Clerk" },
  { value: "BRANCH_MANAGER", label: "Branch Manager" },
  { value: "BRANCH_OPERATIONS_MANAGER", label: "Branch Operations Manager" },
  { value: "BUSINESS_CORRESPONDENT", label: "Business Correspondent" },
  {
    value: "CARD_OPERATIONS_EXECUTIVE",
    label: "Card Operations Executive / Lead",
  },
  { value: "CASHIER", label: "Cashier" },
  { value: "PERSONAL_BANKER", label: "Personal Banker" },
  { value: "PHONE_BANKING_OFFICER", label: "Phone Banking Officer" },
  { value: "REGIONAL_MANAGER", label: "Regional Manager" },
  { value: "RELATIONSHIP_MANAGER", label: "Relationship Manager" },
  { value: "SALES_OFFICER", label: "Sales Officer" },
  { value: "BANKING_OPERATIONS_OTHER", label: "Banking Operations - Other" },
  { value: "GENERAL_INSURANCE", label: "General Insurance" },
  { value: "ACTUARIAL_ANALYST", label: "Actuarial Analyst" },
  { value: "ACTUARIAL_MANAGER", label: "Actuarial Manager" },
  { value: "AGENCY_MANAGER", label: "Agency Manager" },
  { value: "BANCASSURANCE_MANAGER", label: "Bancassurance Manager" },
  { value: "CLAIMS_EXECUTIVE", label: "Claims Executive" },
  { value: "CLAIMS_MANAGER", label: "Claims Manager" },
  { value: "INSURANCE_AGENT_ADVISOR", label: "Insurance Agent / Advisor" },
  { value: "INSURANCE_ANALYST", label: "Insurance Analyst" },
  {
    value: "INSURANCE_OPERATIONS_EXECUTIVE",
    label: "Insurance Operations Executive",
  },
  {
    value: "INSURANCE_OPERATIONS_MANAGER",
    label: "Insurance Operations Manager",
  },
  { value: "INSURANCE_SALES_MANAGER", label: "Insurance Sales / BD Manager" },
  { value: "PRICING_MANAGER", label: "Pricing Manager" },
  { value: "UNDERWRITER", label: "Underwriter" },
  { value: "GENERAL_INSURANCE_OTHER", label: "General Insurance - Other" },
  {
    value: "INVESTMENT_BANKING_PE_VC",
    label: "Investment Banking, Private Equity & VC",
  },
  { value: "HEDGE_FUND_MANAGER", label: "Hedge Fund Manager" },
  { value: "INVESTMENT_BANKING_ANALYST", label: "Investment Banking Analyst" },
  {
    value: "INVESTMENT_BANKING_ASSOCIATE",
    label: "Investment Banking Associate",
  },
  {
    value: "PRINCIPAL_PARTNER_DIRECTOR",
    label: "Principal / Partner / Director",
  },
  { value: "PRIVATE_EQUITY_ANALYST", label: "Private Equity Analyst" },
  { value: "VENTURE_CAPITAL_INVESTOR", label: "Venture Capital Investor" },
  {
    value: "INVESTMENT_BANKING_OTHER",
    label: "Investment Banking, Private Equity & VC - Other",
  },
  { value: "LENDING", label: "Lending" },
  { value: "AGENCY_DEVELOPMENT_MANAGER", label: "Agency Development Manager" },
  { value: "COLLECTION_MANAGER", label: "Collection / Recovery Manager" },
  { value: "CREDIT_ANALYST", label: "Credit Analyst" },
  { value: "CREDIT_MANAGER", label: "Credit Manager" },
  { value: "LOAN_OFFICER", label: "Loan Officer" },
  { value: "RISK_ANALYST", label: "Risk Analyst" },
  { value: "RISK_MANAGER", label: "Risk Manager" },
  { value: "SALES_MANAGER", label: "Sales Manager" },
  { value: "LENDING_OTHER", label: "Lending - Other" },
  { value: "LIFE_INSURANCE", label: "Life Insurance" },
  { value: "LIFE_INSURANCE_OTHER", label: "Life Insurance - Other" },
  {
    value: "TRADING_ASSET_MANAGEMENT",
    label: "Trading, Asset & Wealth Management",
  },
  { value: "FINANCIAL_ADVISOR", label: "Financial Advisor" },
  { value: "PORTFOLIO_MANAGER", label: "Portfolio Manager" },
  { value: "RESEARCH_ANALYST", label: "Research Analyst" },
  { value: "STOCK_BROKER", label: "Stock Broker" },
  { value: "WEALTH_MANAGER", label: "Wealth Manager" },
  {
    value: "TRADING_OTHER",
    label: "Trading, Asset & Wealth Management - Other",
  },
  { value: "TREASURY_FOREX", label: "Treasury & Forex" },
  { value: "FOREX_DEALER", label: "Forex Dealer" },
  { value: "TREASURY_ANALYST", label: "Treasury Analyst" },
  { value: "TREASURY_HEAD", label: "Treasury Head" },
  { value: "TREASURY_OTHER", label: "Treasury & Forex - Other" },
  { value: "CUSTOMER_SUCCESS", label: "Customer Success" },
  { value: "DATA_ANALYST", label: "Data Analyst" },
  { value: "HEAD_ANALYTICS", label: "Head - Analytics / BI" },
  { value: "DATA_SCIENTIST", label: "Data Scientist" },
  { value: "HARDWARE_ENGINEER", label: "Hardware Engineer" },
  { value: "DEVOPS_ENGINEER", label: "DevOps Engineer" },
  { value: "QA_ENGINEER", label: "Quality Assurance Engineer" },
  { value: "SOFTWARE_DEVELOPER", label: "Software Developer" },
  { value: "ACCOUNTANT", label: "Accountant" },
  { value: "AUDITOR", label: "Auditor" },
  { value: "FINANCIAL_ANALYST", label: "Financial Analyst" },
  { value: "TREASURY_MANAGER", label: "Treasury Manager" },
  { value: "FINANCE_OTHER", label: "Finance & Accounting - Other" },
];

export const statusData = [
  { value: "Applied", label: "Applied" },
  { value: "Shortlisted", label: "Shortlisted" },
  { value: "Selected", label: "Selected" },
  { value: "Rejected", label: "Rejected" },
  { value: "CallAfterSometime", label: "Call After Sometime" },
  { value: "AfterSomeMonth", label: "After Some Month" },
  { value: "ExEmployee", label: "Ex Employee" },
  { value: "HigherCTC", label: "Higher CTC" },
  { value: "NotInterested", label: "Not Interested" },
  { value: "OtherLocation", label: "Other Location" },
  { value: "RecentlyChanged", label: "Recently Changed" },
  { value: "Ringing", label: "Ringing" },
  { value: "SwitchedOff", label: "Switched Off" },
  { value: "CVShared", label: "CV Shared" },
  { value: "LineupForInterview", label: "Lineup for the Interview" },
  { value: "NotLookingForChange", label: "Not Looking for Change" },
  { value: "NoShow", label: "No Show" },
  { value: "AgainLineUp", label: "Again Line Up" },
  {
    value: "NotInterestedNowForCompany",
    label: "Not Interested Now for This Company",
  },
  { value: "InterviewDone", label: "Interview Done" },
  { value: "FeedbackAwaited", label: "Feedback Awaited" },
  { value: "OfferLetterAwaited", label: "Offer Letter Awaited" },
  { value: "OfferAccepted", label: "Offer Accepted" },
  { value: "JoiningDate", label: "Joining Date" },
  { value: "Joined", label: "Joined" },
];
